"""create people and entries

Revision ID: 3c3fcbfd13b5
Revises: 
Create Date: 2026-01-22 14:03:43.401246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c3fcbfd13b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province_or_territory', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('hands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_person_id'), 'entries', ['person_id'], unique=False)
    # op.drop_table('dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('handid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('handstr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('score', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('handid', name=op.f('dummy_pkey'))
    )
    op.drop_index(op.f('ix_entries_person_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_table('people')
    # ### end Alembic commands ###
